# Generated by Django 5.1.3 on 2024-12-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coures',
            fields=[
                ('course_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('Coures_name', models.CharField(max_length=128)),
                ('teacher', models.CharField(max_length=128)),
            ],
        ),
    ]
